# Current Work Directory

In [1]:
import os
print(os.getcwd())

/home/alireza/Desktop/Python_Recap


# Types

**Built-in Data Types by Category:**

Text Type:      **str**

Numeric Types:  **int**, **float**, **complex**

Sequence Types: **list**, **tuple**, **range**

Set Types:      **set**, **frozenset**

[List vs Tuple vs Set](https://drive.google.com/uc?export=view&id=1wkiXQgvmyp7sCrytefDKuoDMayYrOPpt)

("frozenset" is immutable version of "set")

Mapping Type:   **dict**

Boolean Type:   **bool**

Binary Types:   **bytes**, **bytearray**, **memoryview**

None Type:      **NoneType**

In [3]:
print('------Text------')

a = 'Hello'
print('\na is {}'.format(a))
print(type(a))

print('\n------Numeric------')

b = '10'
print('\nb is {}'.format(b))
print(type(b))

c = '10.1'
print('\nc is {}'.format(c))
print(type(c))

d = 2j
print('\nd is {}'.format(d))
print(type(d))

print('\n------Sequence------')

e = ["apple", "banana", "cherry"]
print('\ne is {}'.format(e))
print(type(e))

f = ("apple", "banana", "cherry")
print('\nf is {}'.format(f))
print(type(f))

g = range(6)
print('\ng is {}'.format(g))
print(type(g))

print('\n------Set------')

h = {"apple", "banana", "cherry"}
print('\nh is {}'.format(h))
print(type(h))

i = frozenset({"apple", "banana", "cherry"})
print('\ni is {}'.format(i))
print(type(i))

print('\n------Mapping------')

j = {"name" : "John", "age" : 36}
print('\nj is {}'.format(j))
print(type(j))

print('\n------Boolean------')

k = False
print('\nk is {}'.format(k))
print(type(k))

print('\n------Binary------')

l = b"Hello"
print('\nl is {}'.format(l))
print(type(l))

m = bytearray(5)
print('\nm is {}'.format(m))
print(type(m))

n = memoryview(bytes(5))
print('\nn is {}'.format(n))
print(type(n))

print('\n------None------')

o = None
print('\no is {}'.format(o))
print(type(o))

------Text------

a is Hello
<class 'str'>

------Numeric------

b is 10
<class 'str'>

c is 10.1
<class 'str'>

d is 2j
<class 'complex'>

------Sequence------

e is ['apple', 'banana', 'cherry']
<class 'list'>

f is ('apple', 'banana', 'cherry')
<class 'tuple'>

g is range(0, 6)
<class 'range'>

------Set------

h is {'banana', 'apple', 'cherry'}
<class 'set'>

i is frozenset({'banana', 'apple', 'cherry'})
<class 'frozenset'>

------Mapping------

j is {'name': 'John', 'age': 36}
<class 'dict'>

------Boolean------

k is False
<class 'bool'>

------Binary------

l is b'Hello'
<class 'bytes'>

m is bytearray(b'\x00\x00\x00\x00\x00')
<class 'bytearray'>

n is <memory at 0x7f399c348940>
<class 'memoryview'>

------None------

o is None
<class 'NoneType'>


# Conditionals

In [ ]:
x = 435.10
y = 435.4

if x < y:
    print('x < y: x is {} and y is {}'.format(x, y))

x < y: x is 435.1 and y is 435.4


In [ ]:
a = True
b = False

if a and b:
    print('Expression is true')
else:
    print('Expression is false')

Expression is false


# For Loop

In [ ]:
words = ['one', 'two', 'three', 'four', 'five']

for i in words:
    print(i)

print('\n')

for i in enumerate(words):
    print(i)

print('\n')

for i in range(len(words)):
    print(i)

print('\n')

one
two
three
four
five


(0, 'one')
(1, 'two')
(2, 'three')
(3, 'four')
(4, 'five')


0
1
2
3
4




# While Loop

In [ ]:
# A recurrence relation: simple fibonacci series
a, b = 0, 1
while b < 1000:
    print(b, end = ' ', flush = True)
    a, b = b, a + b

1 1 2 3 5 8 13 21 34 55 89 144 233 377 610 987 

In [ ]:
secret = 'Python'
password = ''

while password != secret:
    password = input("What's the password? ") 
else:
  print("Passeord is correct!")

What's the password? python
What's the password? Python
Passeord is correct!


# Function

In [6]:
def sum(a,b):
    c = a+b
    return print('Sum is {}'.format(c))

sum(1,2)

Sum is 3


In [11]:
# Get Python version
import platform

def message():
    print('This is python version {}'.format(platform.python_version()))

def main():
    message()

if __name__ == '__main__': main()

This is python version 3.7.13


# Function + Conditional + For

In [12]:
def isprime(n):
    if n <= 1:
        return False
    for x in range(2, n):
        if n % x == 0:
            return False
    else:
        return True

n = 5
if isprime(n):
    print(f'{n} is prime')
else:
    print(f'{n} not prime')

5 is prime


In [13]:
hungry = True
x = 'Feed the python now!' if hungry else 'Do not feed the python.'
print(x)

Feed the python now!


# Class

In [14]:
class anaconda:
    def sounds(self):
        print('Hisses like a snake!')

    def moves(self):
        print('Slithers like a snake!')

In [15]:
python = anaconda()
python.sounds()
print('-----')
python.moves()

Hisses like a snake!
-----
Slithers like a snake!


In [16]:
def main():
    cobra = anaconda()
    cobra.sounds()
    cobra.moves()

if __name__ == '__main__': main()

Hisses like a snake!
Slithers like a snake!


In [ ]:
class snake:
  def __init__(self, s, l):
    self.specie = s
    self.length = l

anaconda = snake("Python", 2)

print(anaconda.specie)
print('-----')
print(anaconda.length) 
print('-----')
print(type(anaconda)) 

Python
-----
2
-----
<class '__main__.snake'>


# args

In [ ]:
def my_sum(my_integers):
    result = 0
    for x in my_integers:
        result += x
    return result

list_of_integers = [1, 2, 3]
print(my_sum(list_of_integers))

# This is where *args can be really useful, because it allows you to pass 
# a varying number of positional arguments:
def my_sum(*integers):
    result = 0
    for x in integers:
        result += x
    return result

print(my_sum(1, 2, 3))


6


In [ ]:
# another example
def main():
    kitten('meow', 'grrr', 'purr') # kitten()

def kitten(*args):
    if len(args):
        for s in args:
            print(s)
    else: print('Meow.')

if __name__ == '__main__': main()

meow
grrr
purr


# kwargs

In [ ]:
def main():
    kitten(Honey = 'meow', Daisy = 'grr', Ed = 'rawr')

def kitten(**kwargs):
    if len(kwargs):
        for k in kwargs:
            print('Kitten {} says {}.'.format(k, kwargs[k]))
    else: print('Meow.')

if __name__ == '__main__': main()

Kitten Honey says meow.
Kitten Daisy says grr.
Kitten Ed says rawr.


# Decorator

In [ ]:
#### @decorator
#### def func():
####     ...
 
# is equivalent to:
 
#### def func():
####     …
#### func = decorator(func)

# A simple decorator:
# takes a function as argument and returns a new function that behaves like the
# original function, except it prints the function name and argument for every call
def trace(f):
    def g(*args):
        print(f.__name__, args)
        return f(*args)
    return g

@trace
def square(x):
    return x*x

@trace
def sum_of_squares(x, y):
    return square(x) + square(y)

square(3,)
# print('-----')
# sum_of_squares (3, 4)

square (3,)


9

In [ ]:
import time
import builtins # sometimes need it sometimes dont depending on your platform

def elapsed_time(f):
    def wrapper():
        t1 = time.time()
        f()
        t2 = time.time()
        print(f'Elapsed time: {(t2 - t1) * 1000} ms')
    return wrapper

@elapsed_time
def big_sum():
    num_list = []
    for num in (range(0, 10000)):
        num_list.append(num)
    print(f'Big sum: {builtins.sum(num_list)}')

def main():
    big_sum()

if __name__ == '__main__': main()

Big sum: 49995000
Elapsed time: 4.736423492431641 ms


# NumPy

In [ ]:
# conda install numpy
# or
# pip install numpy

# To access NumPy and its functions import it in your Python code like below.
# We shorten the imported name to "np" for better readability of code
import numpy as np 

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print('\n-----1-----\n')
print(a)
print('\n-----2-----\n')
print(a[1])
print('\n-----3-----\n')
print(a[1][2])
print('\n-----4-----\n')

# uninitialized empty array
b = np.empty([2, 2], dtype=int)
print(b)
print('\n-----5-----\n')

# Initialized array
b = np.zeros([2, 2], dtype=int)
print(b)
print('\n-----6-----\n')
print(b.shape)
print('\n-----7-----\n')
print(type(b))

# print(a+b) # gives error

b = np.ones(a.shape)
print('\n-----8-----\n')
print(a+b)


-----1-----

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

-----2-----

[5 6 7 8]

-----3-----

7

-----4-----

[[10 10]
 [10 10]]

-----5-----

[[0 0]
 [0 0]]

-----6-----

(2, 2)

-----7-----

<class 'numpy.ndarray'>

-----8-----

[[ 2.  3.  4.  5.]
 [ 6.  7.  8.  9.]
 [10. 11. 12. 13.]]


[NumPy Cheat Sheet](https://drive.google.com/uc?export=view&id=1lXouM5dLcDD3gfkmBy0iEZ4F2rlPAQlF)

# pandas

In [ ]:
import pandas as pd

print('\n-----1-----\n')
print(pd.__version__)

df = pd.DataFrame({'num_legs': [2, 4, 2], 'num_wings': [2, 0, 0]}, index=['falcon', 'dog', 'human'])

print('\n-----2-----\n')
print(df.info())

print('\n-----3-----\n')
print(df.head(n=10))

print('\n-----4-----\n')
print(df.tail(n=1))

print('\n-----5-----\n')
print(df['num_legs']+df['num_wings'])

print('\n-----6-----\n')
print(df.dtypes)

print('\n-----7-----\n')
data = np.array([(1, 2, 3), (4, 5, 6), (7, 8, 9)], dtype=[("a", "i4"), ("b", "i4"), ("c", "i4")])
df2 = pd.DataFrame(data, columns=['c', 'a'])
df2.head()

# can use "astype" to change type
# df = df.astype({'c': 'int64', 'a': 'int64'})


-----1-----

1.3.5

-----2-----

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, falcon to human
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   num_legs   3 non-null      int64
 1   num_wings  3 non-null      int64
dtypes: int64(2)
memory usage: 72.0+ bytes
None

-----3-----

        num_legs  num_wings
falcon         2          2
dog            4          0
human          2          0

-----4-----

       num_legs  num_wings
human         2          0

-----5-----

falcon    4
dog       4
human     2
dtype: int64

-----6-----

num_legs     int64
num_wings    int64
dtype: object

-----7-----



c  a
0  3  1
1  6  4
2  9  7

[pandas Cheat Sheet](https://drive.google.com/uc?export=view&id=1L81o_jIPaRMXnfSjlwwBfdXi3cqB2sdd)