# Lab 1

Jupyter Notebook is an open source web application that you can use to create and share documents that contain live code, equations, visualizations, and text. In this lab we provide an introduction to Python.

## Basic Python Instances

**Python Operatos:** https://www.w3schools.com/python/python_operators.asp

In [1]:
print("Hello World")

Hello World


In [2]:
# Variable names can start with a letter or _, but not a number or any other operator.
hello = "Hello World"
print(hello)

Hello World


In [3]:
x = 5 
y = 7

In [4]:
x + 7

12

In [5]:
y + 2

9

In [6]:
# Operators +, -, *, /, **
print(x + 7)

12


In [7]:
y ** 2

49

A class has objects which belong to it and their classs is refered to as their "type".

In [8]:
# Printing multiple things by seperating them with a ,
print("Variable x is:", type(x), "Variable hello is:", type(hello))

Variable x is: <class 'int'> Variable hello is: <class 'str'>


## Data Structures

**Dictionaries:** https://www.w3schools.com/python/python_dictionaries.asp

In [9]:
# Dictionaries have a Key and a value.
dict_1 = {"Stats" : "Happy"}
print("The dictionay holds", dict_1, "and the 'Stats' value is:", dict_1["Stats"])

The dictionay holds {'Stats': 'Happy'} and the 'Stats' value is: Happy


In [10]:
# Update allows you to add more dictionaries to an existing one dynamically making the original one bigger.
dict_2 = {"Math" : "Exited"}
dict_1.update(dict_2)
print(dict_1)

{'Stats': 'Happy', 'Math': 'Exited'}


**Python lists:** https://www.w3schools.com/python/python_lists.asp

In [11]:
# List is a subscriptable object that holds data of any type.
list_1 = [1, 2, 3]
print(list_1)

[1, 2, 3]


In [12]:
list_1.append(5)
print(list_1)

[1, 2, 3, 5]


In [13]:
# Python lists are 0-indexed. So the first element is 0, second is 1, and so on.
# So if there are n elements in a list, the last element is n - 1.
list_1[0]

1

**Pandas:** https://pandas.pydata.org/docs/ <br/>
**Numpy:** https://numpy.org/doc/1.20/user/absolute_beginners.html

In [14]:
# The Python language has only very basic operations. Most math functions are in various math libraries.
# The numpy and pandas are convenient libraries. We can import numpy with the prefix np, and pandas with the prefix pd.
import pandas as pd
import numpy as np

**pd.DataFrame:** https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html

In [15]:
df_data = {"Age" : [1, 2], "Height" : [3, 4]}
df = pd.DataFrame(data = df_data)
df

Age  Height
0    1       3
1    2       4

In [16]:
df["Weight"] = [2, 5]
df

Age  Height  Weight
0    1       3       2
1    2       4       5

In [17]:
# Extracting specific data point (second row and third column)
print(df.iloc[1, 2])

5


In [18]:
print(df["Age"])

0    1
1    2
Name: Age, dtype: int64


In [19]:
# Extracting a specific row
df[df["Age"] == 2]

Age  Height  Weight
1    2       4       5

In [20]:
# Another way to extract a specific row
df[df.Age == 2]

Age  Height  Weight
1    2       4       5

In [21]:
# Showing the whole dataframe
df.iloc[:]

Age  Height  Weight
0    1       3       2
1    2       4       5

In [22]:
# Showing the first row
df.iloc[0, :]

Age       1
Height    3
Weight    2
Name: 0, dtype: int64

In [23]:
# Showing the second column
df.iloc[:, 1]

0    3
1    4
Name: Height, dtype: int64

**np.array**: https://numpy.org/doc/stable/reference/generated/numpy.array.html

In [24]:
# Creating 2D arrays
arr_1 = np.array([[1, 2], [3, 2]])
arr_2 = np.array([[5, 4], [6, 7]])
print("arr_1 = \n", arr_1, "\narr_2 = \n", arr_2)

arr_1 = 
 [[1 2]
 [3 2]] 
arr_2 = 
 [[5 4]
 [6 7]]


In [25]:
print("Shape of arr_1:", np.shape(arr_1))
print("Shape of arr_2:", np.shape(arr_2))

Shape of arr_1: (2, 2)
Shape of arr_2: (2, 2)


In [26]:
# Array operators
print("dot product:\n", arr_1 @ arr_2)

dot product:
 [[17 18]
 [27 26]]


In [27]:
# Elementwise exponential
print("exponents:\n", arr_1 ** 2)

exponents:
 [[1 4]
 [9 4]]


In [28]:
# Elementwise multiplication
print("scalars\n", arr_1 * 5)

scalars
 [[ 5 10]
 [15 10]]


In [29]:
# Array of given shape and type filled with ones
print("Array with entries of 1: \n", np.ones((3, 3)))

Array with entries of 1: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [30]:
# Array of given shape and type filled with zeros
print("Array with entries of 0: \n", np.zeros((3, 3)))

Array with entries of 0: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [31]:
# Evenly spaced numbers over a specified interval
print("Sequence:\n", np.linspace(2, 9, 8))

Sequence:
 [2. 3. 4. 5. 6. 7. 8. 9.]


In [32]:
# A sorted copy of an array
print("Sorted arr_1:\n", np.sort(arr_1))

Sorted arr_1:
 [[1 2]
 [2 3]]
